server:
  port: 9002

spring:
  application:
    name: file

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

#fastdfs相关
fdfs:
  tracker-list:  # 可配置多个
    - localhost:22122
  web-server-url: http://localhost:8888/
