server:
  port: 9004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: user
  devtools:
    livereload:
      port: 35734
  datasource:
    druid:  # 集成druid连接池
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456

# 资源服务器配置
resource:
  key-location: key/public.key
  white-list:
    - /images/**
    - /js/**
    - /css/**
    - /user/info/load/**
