server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: order
  devtools:
    livereload:
      port: 35732
  datasource:
    druid:  # 集成druid连接池
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
  main:
    allow-bean-definition-overriding: true  # 可能会出现相同名称的FeignClient，加上避免编译报错
  redis:
    host: localhost

snowflake:
  datacenter-id: 2
  worker-id: 1

# 资源服务器配置
resource:
  key-location: key/public.key
  white-list:
    - /images/**
    - /js/**
    - /css/**