server:
  port: 9004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: order
  devtools:
    livereload:
      port: 35734
  datasource:
    druid:  # 集成druid连接池
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
  main:
    allow-bean-definition-overriding: true  # 可能会出现相同名称的FeignClient，加上避免编译报错
  redis:
    host: localhost

#  feign:
#    hystrix:
#      enabled: true
#    client:
#      config:
#        default: #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
#          connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
#          readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#  #hystrix 配置
#  hystrix:
#    command:
#      default:
#        execution:
#          timeout:
#            #如果enabled设置为false，则请求超时交给ribbon控制
#            enabled: true
#          isolation:
#            strategy: SEMAPHORE
#            thread:
#              # 熔断器超时时间，默认：1000/毫秒
#              timeoutInMilliseconds: 20000

snowflake:
  datacenterId: 4
  workerId: 1

# 资源服务器配置
resource:
  public-key: key/public.key
#  ignoring-urls: ,

# 购物车缓存key前缀
cart-key-prefix: cart_