server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: system
  devtools:
    livereload:
      port: 35733
  datasource:
    druid:  # 集成druid连接池
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456

snowflake:
  datacenterId: 3
  workerId: 1