server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: goods
  devtools:
    livereload:
      port: 35731
  datasource:
    druid:  # 集成druid连接池
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
  main:
    allow-bean-definition-overriding: true  # 允许覆盖注册，开启，否则ESSkuMapper可能编译报错
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  rabbitmq:
    host: localhost

snowflake:
  datacenter-id: 1
  worker-id: 1

# 资源服务器配置
resource:
  key-location: key/public.key
  white-list:
    - /images/**
    - /js/**
    - /css/**
    - /user/info/load/**
    - /user/info/login