server:
  port: 9005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: pay
  devtools:
    livereload:
      port: 35735

snowflake:
  datacenter-id: 5
  worker-id: 1