server:
  port: 9100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: auth
  devtools:
    livereload:
      port: 35829
  datasource:
    druid: # 集成druid连接池
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall_oauth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
  redis:
    host: localhost
  main:
    allow-bean-definition-overriding: true

# 授权服务器自定义配置
authentication:
  key-store: # 授权服务器（私钥）
    location: classpath:/key/mall.jks  # 密钥库位置
    store-pass: storepass  # 密钥库密码
    alias: mall  # 密钥别名
    key-pass: keypass  # 密钥密码
  white-list:
    - /auth/login
    - /auth/logout
  authorities:
    - admin
  jwt-timeout: 1200  # redis过期时间，s
  cookie-domain: localhost  # cookie域名
  cookie-max-age: -1  # cookie过期时间，-1表示浏览器关闭才销毁

