server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway
  devtools:
    livereload:
      port: 35729  # 默认值
  cloud:
    gateway:
      globalcors:  # 网关跨域请求配置（各微服务仍需单独配置）
        cors-configurations:
          '[/**]':  # 所有请求
            allowedOrigins: "*"  # 所有域
            allowedMethods:  # 所有方法
              - GET
              - POST
              - PUT
              - DELETE
      loadbalancer:
        use404: true  # 无法找到服务实例时由404替代默认的503
      routes:   # 路由
        # 商品微服务
        - id: goods
          uri: lb://goods  # 负载均衡
          predicates:
            - Path=/goods/**
          filters:
            - name: RequestRateLimiter
              # 指定每秒最多2个请求
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1  # 令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 2  # 令牌桶总容量
        # 系统管理微服务
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
        # 用户微服务
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        # 订单微服务
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
        # 前台微服务（测试用）
        - id: web
          uri: lb://web
          predicates:
            - Path=/web/**
        # 授权微服务
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
  redis:
    host: localhost

gateway:
  jwt-key: mallSystem  # jwt签发密钥（本项目中仅对系统微服务签发）
  black-list:  # 黑名单
    - 192.168.200.1
  white-list:  # 白名单
    - /system/admin/login
    - /auth/login
