server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: web
  devtools:
    livereload:
      enabled: false
  main:
    allow-bean-definition-overriding: true